from controllers.UserController import UserController
from controllers.AlbumController import AlbumController
from controllers.ArtistController import ArtistController
from controllers.PlaylistController import PlaylistController
from controllers.SongController import SongController
from controllers.SubscriptionController import SubscriptionController
from controllers.SubscriptionTypeController import SubscriptionTypeController
from controllers.PlaylistHasSongController import PlaylistHasSongController
